# Generated by Django 2.1.5 on 2019-08-24 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curs',
            name='image_video',
            field=models.ImageField(null=True, upload_to='image/curs_video/'),
        ),
        migrations.AddField(
            model_name='lessons',
            name='lesson_id',
            field=models.SmallIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='lessons',
            name='title',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='video_lessons',
            name='title',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='curs',
            name='number_lessons',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
