# Generated by Django 2.1.5 on 2019-08-24 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190824_0731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessons',
            name='lesson_id',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
