# Generated by Django 2.1.5 on 2019-08-25 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190824_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='curs_students',
            name='block',
            field=models.SmallIntegerField(null=True),
        ),
    ]
