# Generated by Django 2.1.5 on 2019-08-29 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_curs_students_block'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='teacher',
            field=models.IntegerField(max_length=60, null=True),
        ),
    ]
