# Generated by Django 2.1.5 on 2019-08-31 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20190829_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='answer1',
            field=models.CharField(max_length=550),
        ),
        migrations.AlterField(
            model_name='test',
            name='answer2',
            field=models.CharField(max_length=550),
        ),
        migrations.AlterField(
            model_name='test',
            name='answer3',
            field=models.CharField(max_length=550),
        ),
        migrations.AlterField(
            model_name='test',
            name='answer4',
            field=models.CharField(max_length=550),
        ),
        migrations.AlterField(
            model_name='test',
            name='answer5',
            field=models.CharField(max_length=550),
        ),
        migrations.AlterField(
            model_name='test',
            name='name',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='school',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='teacher',
            field=models.IntegerField(null=True),
        ),
    ]
