# Generated by Django 2.1.5 on 2019-09-03 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20190903_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='teacher',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
