# Generated by Django 2.1.5 on 2019-09-03 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20190903_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.BigIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='teacher',
            field=models.IntegerField(null=True),
        ),
    ]
