# Generated by Django 2.1.5 on 2019-09-14 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20190914_0632'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='points',
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
    ]
