# Generated by Django 2.1.5 on 2019-11-21 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_curs_type_curs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursedata',
            name='developer',
            field=models.CharField(max_length=600, null=True),
        ),
    ]
