# Generated by Django 2.2.3 on 2019-12-07 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_userprofile_layer'),
    ]

    operations = [
        migrations.AddField(
            model_name='test_student',
            name='status',
            field=models.SmallIntegerField(default=0),
        ),
    ]
